version: "3.8"

services:
  nest:
    container_name: nest
    build: .
    image: nestapp:nest
    tty: true
    stdin_open: true
    ports:
      - 3000:3000
    volumes:
      # According to https://stackoverflow.com/a/40905828/5026 you can use `.`
      # for a path relative to the docker-compose.yml file.
      - .:/app
